.DEFUALT : build

build:
	cp dnsserver.py dnsserver
	chmod +x dnsserver
	cp httpserver.py httpserver
	chmod +x httpserver
	cp deployCDN.py deployCDN
	chmod +x deployCDN
	cp runCDN.py runCDN
	chmod +x runCDN
	cp stopCDN.py stopCDN
	chmod +x stopCDN
	cp cacheFill.py cacheFill
	chmod +x cacheFill